---
title: "Final Project 741: Fruit and Vegetable Intake is associated with a family history of cancer"
author: "Jennifer Frediani"
date: "3/4/2020"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
```{r}
#load data from SPSS
library(ggplot2)
library(dplyr)
library(haven)
library(tableone)
library(foreign)
library(GGally)
library(ROCR)
library(pROC)
hints4cycle2_09062017_public_edited <- read_sav("~/CPTR-NRSG 741/FInal-Project/hints4cycle2_09062017_public_edited.sav")
hints4cycle2_foreign_factor <-read.spss("~/CPTR-NRSG 741/HINTS4-Cycle2-SPSS/hints4cycle2_09062017_public.sav", use.value.labels = TRUE, to.data.frame = TRUE) 

hints4cycle2_foreign_df <- read.spss("~/CPTR-NRSG 741/HINTS4-Cycle2-SPSS/hints4cycle2_09062017_public.sav", use.value.labels = FALSE, to.data.frame = TRUE)

hints4cycle2 <- hints4cycle2_09062017_public_edited
```


```{r}
#Data Wrangling

#subset full dataset for just the variables I need
hints_factor <- select(hints4cycle2_foreign_factor, FamilyEverHadCancer, EverHadCancer, CaProstate, smokeStat, Education, HowLongModerateExerciseMn, HowLongModerateExerciseHr, TimesModerateExercise, TimesStrengthTraining, Fruit, Vegetables, GenderC, MaritalStatus, HHInc, RaceEthn, Age)

hints_df <- select(hints4cycle2_foreign_df, FamilyEverHadCancer, EverHadCancer, CaProstate, smokeStat, Education, HowLongModerateExerciseMn, HowLongModerateExerciseHr, TimesModerateExercise, TimesStrengthTraining, Fruit, Vegetables, GenderC, MaritalStatus, HHInc, RaceEthn, Age)

#Recoding missing values
# new variables
# These now have no negative missing codes, all missing are set to NA


hints2_factor <- hints_factor %>%
  mutate(ExerciseModMn0 = ifelse(HowLongModerateExerciseMn < 0, NA, HowLongModerateExerciseMn),
         ExerciseModHr0 = ifelse(HowLongModerateExerciseHr < 0, NA, HowLongModerateExerciseHr),
         ExerciseModDays0 = ifelse(TimesModerateExercise < 1, NA, TimesModerateExercise),
         TimesStrengthTraining0 = ifelse(TimesStrengthTraining < 0, NA, TimesStrengthTraining),
         Education0 = ifelse(Education < 0, NA, Education),
         smokeStat0 = ifelse(smokeStat < 0, NA, smokeStat),
         CaProstate0 = ifelse(CaProstate < 0, NA, CaProstate),
         FamilyEverHadCancer0 = ifelse(((FamilyEverHadCancer < 0) | (FamilyEverHadCancer ==4)), NA, FamilyEverHadCancer),
         Fruit0 = ifelse(Fruit < 0, NA, Fruit),
         Vegetables0 = ifelse(Vegetables < 0, NA, Vegetables),
         EverHadCancer0 = ifelse(EverHadCancer < 0, NA, EverHadCancer), 
         GenderC0 = ifelse(GenderC < 0, NA, GenderC),
         MaritalStatus0 = ifelse(MaritalStatus < 0, NA, MaritalStatus),
         HHInc0 = ifelse(HHInc < 0, NA, HHInc),
         RaceEthn0 = ifelse(RaceEthn < 0, NA, RaceEthn),
         Age0 = ifelse(as.numeric(Age) < 0, NA, Age))

hints2_df <- hints_df %>%
  mutate(ExerciseModMn0 = ifelse(HowLongModerateExerciseMn < 0, NA, HowLongModerateExerciseMn),
         ExerciseModHr0 = ifelse(HowLongModerateExerciseHr < 0, NA, HowLongModerateExerciseHr),
         ExerciseModDays0 = ifelse(TimesModerateExercise < 1, NA, TimesModerateExercise),
         TimesStrengthTraining0 = ifelse(TimesStrengthTraining < 0, NA, TimesStrengthTraining),
         Education0 = ifelse(Education < 0, NA, Education),
         smokeStat0 = ifelse(smokeStat < 0, NA, smokeStat),
         CaProstate0 = ifelse(CaProstate < 0, NA, CaProstate),
         FamilyEverHadCancer0 = ifelse(((FamilyEverHadCancer < 0) | (FamilyEverHadCancer ==4)), NA, FamilyEverHadCancer),
         Fruit0 = ifelse(Fruit < 0, NA, Fruit),
         Vegetables0 = ifelse(Vegetables < 0, NA, Vegetables),
         EverHadCancer0 = ifelse(EverHadCancer < 0, NA, EverHadCancer), 
         GenderC0 = ifelse(GenderC < 0, NA, GenderC),
         MaritalStatus0 = ifelse(MaritalStatus < 0, NA, MaritalStatus),
         HHInc0 = ifelse(HHInc < 0, NA, HHInc),
         RaceEthn0 = ifelse(RaceEthn < 0, NA, RaceEthn),
         Age0 = ifelse(as.numeric(Age) < 0, NA, Age))
   

#Fruit and Vegetables need to be added together to create a new variable to compare to the guidelines in cups

# Calculate exercise and compare to the PA guidelines 

hints_addvars <- hints2_df %>%
  mutate(totalmin = (ExerciseModMn0 + (ExerciseModHr0*60)) * ExerciseModDays0)
hints_addvars2 <- hints_addvars %>%
  mutate(FruitVeg0 = Fruit0 + Vegetables0)

```

```{r}
# split into training and testing dataset
# generate random numbers uniform distribution
# from 0 to 1 for every row in dataset
hints_addvars2$FamilyEverHadCancer0.f <-
set.seed(20170208)
hints_addvars2$group <- runif(length(hints_addvars2$FamilyEverHadCancer0), 
                      min = 0, max = 1)
# plot of random numbers
hist(hints_addvars2$group)

# split dataset into training (80% of data)
# and testing (20% of data)
hints.train <- subset(hints_addvars2, group <= 0.80)
hints.test <- subset(hints_addvars2, group > 0.80)

```

```{r}
# Table 1 coding
head(hints2_df)
#list numerically coded categorical variables
factorVars <- c( "smokeStat", "GenderC", "Education", "MaritalStatus",  "RaceEthn", "HHInc")
#Creating variable list
vars <- c("Age", "GenderC", "RaceEthn", "MaritalStatus","Education", "HHInc",  "smokeStat", "Fruit", "Vegetables", "TimesModerateExercise", "TimesStrengthTraining" )

tableOne <- CreateTableOne(vars = vars,  data = hints_addvars2, strata = c("EverHadCancer0"), factorVars = factorVars)
kableone(tableOne)

tableTwo <- CreateTableOne(vars = vars, strata = c("FamilyEverHadCancer0"), data = hints_addvars2, factorVars = factorVars)
kableone(tableTwo)

```

```{r}
#Figure 1 coding

ggplot(hints_addvars2, aes(as.character(FamilyEverHadCancer0)))+ geom_bar(stat="count") + 
  xlab("Family History of Cancer")+
  ylab("Count")+
  scale_x_discrete(breaks = c(1,2,NA),
                     labels = c("Yes", "No", "Missing"))

ggplot(hints_addvars2, aes(as.character(EverHadCancer0))) + geom_bar(stat="count") + 
  xlab("Current Cancer")+
  ylab("Count")+
  scale_x_discrete(breaks = c(1,2,NA),
                     labels = c("Yes", "No", "Missing"))
```

```{r}
#Figure 2 Coding
Fig2 <- hints_addvars2 %>%
  select(EverHadCancer0, FruitVeg0, ExerciseModDays0, TimesStrengthTraining0, Education0, smokeStat0, Age0)

ggpairs(Fig2, aes(color=as.character(EverHadCancer0)))
```



```{r}
#Family History model training set

FHxmodtrainFV <- glm(as.factor(FamilyEverHadCancer0) ~ FruitVeg0 + Education0 + Age0 + smokeStat0, data = hints.train, family = binomial)
summary(FHxmodtrainFV)
exp(coef(FHxmodtrainFV))
exp(confint(FHxmodtrainFV))

FHxmodtrainEx <- glm(as.factor(FamilyEverHadCancer0) ~ ExerciseModDays0 + Education0 + Age0 + smokeStat0, data = hints.train, family = binomial)
summary(FHxmodtrainEx)
exp(coef(FHxmodtrainEx))
exp(confint(FHxmodtrainEx))

#prediction probabilities
FHxFV.predict <- predict(FHxmodtrainFV, newdata = hints.test, type="response")
plot(hints.test$FruitVeg0,FHxFV.predict)
abline(0.2, 0, col = "red")

FHxEx.predict <- predict(FHxmodtrainEx, newdata = hints.test, type="response")
plot(hints.test$ExerciseModDays0,FHxEx.predict)
abline(0.2, 0, col = "red")

#confusion matrices
table(as.factor(hints.test$FamilyEverHadCancer0), FHxFV.predict > 0.2)

table(as.factor(hints.test$FamilyEverHadCancer0), FHxEx.predict > 0.2)

#ROC curves

p <- predict(FHxmodtrainFV, newdata = hints.test, 
             type="response")
roccurve.FHxFV <- roc(hints.test$FamilyEverHadCancer0 ~ p)
plot(roccurve.FHxFV)
auc(roccurve.FHxFV)

p <- predict(FHxmodtrainEx, newdata = hints.test, 
             type="response")
roccurve.FHxEx <- roc(hints.test$FamilyEverHadCancer0 ~ p)
plot(roccurve.FHxEx)
auc(roccurve.FHxEx)



```
```{r}
#Current Cancer model training set

CamodtrainFV <- glm(as.factor(EverHadCancer0) ~ FruitVeg0 + Education0 + Age0 + smokeStat0, data = hints.train, family = binomial)
summary(CamodtrainFV)
exp(coef(CamodtrainFV))
exp(confint(CamodtrainFV))

CamodtrainEx <- glm(as.factor(EverHadCancer0) ~ ExerciseModDays0 + Education0 + Age0 + smokeStat0, data = hints.train, family = binomial)
summary(CamodtrainEx)
exp(coef(CamodtrainEx))
exp(confint(CamodtrainEx))

#prediction probabilities
CaFV.predict <- predict(CamodtrainFV, newdata = hints.test, type="response")
plot(hints.test$FruitVeg0,CaFV.predict)
abline(0.5, 0, col = "red")

CaEx.predict <- predict(CamodtrainEx, newdata = hints.test, type="response")
plot(hints.test$ExerciseModDays0,CaEx.predict)
abline(0.5, 0, col = "red")

#confusion matrices
table(hints.test$EverHadCancer0, CaFV.predict > 0.5)

table(hints.test$EverHadCancer0, CaEx.predict > 0.5)

#ROC curves
p <- predict(CamodtrainFV, newdata = hints.test, 
             type="response")
roccurve.CaFV <- roc(hints.test$EverHadCancer0 ~ p)
plot(roccurve.CaFV)
auc(roccurve.CaFV)

p <- predict(CamodtrainEx, newdata = hints.test, 
             type="response")
roccurve.CaEx <- roc(hints.test$EverHadCancer0 ~ p)
plot(roccurve.CaEx)
auc(roccurve.CaEx)
```
